# Generated by Django 4.2.11 on 2024-04-19 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('L', 'Lesson'), ('M', 'Minute'), ('S', 'Set'), ('P', 'Page')], default='M', max_length=1)),
                ('type', models.CharField(choices=[('CNS', 'Constant'), ('CRS', 'Course'), ('BOK', 'Book')], default='CNS', max_length=3)),
                ('name', models.CharField(max_length=200)),
                ('number_of_lessons', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.activity')),
            ],
        ),
    ]
