# Generated by Django 4.2.11 on 2024-04-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='number_of_lessons',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
